import { Property } from './types';

export const PROPERTIES: Property[] = [
  {
    id: 'p001',
    title: 'Charmerende villa med stor have',
    address: 'Hasseris Engvej 45',
    city: 'Aalborg',
    postalCode: '9000',
    price: 3_295_000,
    monthlyPayment: 11_800,
    type: 'villa',
    area: 162,
    landArea: 820,
    rooms: 6,
    bathrooms: 2,
    yearBuilt: 1963,
    energyLabel: 'D',
    images: [
      'https://picsum.photos/seed/p001a/800/600',
      'https://picsum.photos/seed/p001b/800/600',
    ],
    description: 'Smuk og velholdt villa i det populære Hasseris-kvarter. Boligen byder på en stor og solrig have med terrasse, nyrenoveret badeværelse og en åben stue med brændeovn. Tæt på gode skoler og indkøbsmuligheder.',
    features: ['Stor have', 'Brændeovn', 'Nyrenoveret badeværelse', 'Garage', 'Terrasse', 'Solrig grund'],
    daysOnMarket: 12,
    agent: { name: 'Mette Christensen', company: 'Nybolig Aalborg', phone: '98 12 34 56' },
  },
  {
    id: 'p002',
    title: 'Moderne lejlighed i centrum',
    address: 'Boulevarden 12, 3. tv.',
    city: 'Aalborg',
    postalCode: '9000',
    price: 1_595_000,
    monthlyPayment: 5_800,
    type: 'lejlighed',
    area: 78,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 2008,
    energyLabel: 'B',
    images: [
      'https://picsum.photos/seed/p002a/800/600',
      'https://picsum.photos/seed/p002b/800/600',
    ],
    description: 'Lys og moderne lejlighed med udsigt over gaden i hjertet af Aalborg. Flot køkken-alrum, nyrenoveret og klar til indflytning. Elevator og cykelkælder i ejendommen.',
    features: ['Altan', 'Elevator', 'Nyrenoveret', 'Parkering', 'Cykelkælder', 'Centralvarme'],
    daysOnMarket: 5,
    agent: { name: 'Lars Pedersen', company: 'EDC Aalborg', phone: '98 23 45 67' },
  },
  {
    id: 'p003',
    title: 'Hyggelig rækkehus med have',
    address: 'Skovvangen 8',
    city: 'Aalborg',
    postalCode: '9000',
    price: 1_895_000,
    monthlyPayment: 6_800,
    type: 'rækkehus',
    area: 112,
    landArea: 240,
    rooms: 4,
    bathrooms: 2,
    yearBuilt: 1991,
    energyLabel: 'C',
    images: [
      'https://picsum.photos/seed/p003a/800/600',
      'https://picsum.photos/seed/p003b/800/600',
    ],
    description: 'Velholdt rækkehus i populær bofællesskab. Lyse og luftige rum, opdateret køkken og to badeværelser. Lille hyggelig have mod syd med terrasse.',
    features: ['Have mod syd', 'Terrasse', 'Opdateret køkken', '2 badeværelser', 'Parkering', 'Varmepumpe'],
    daysOnMarket: 20,
    agent: { name: 'Sofie Andersen', company: 'Home Aalborg', phone: '98 34 56 78' },
  },
  {
    id: 'p004',
    title: 'Andelslejlighed tæt på havnen',
    address: 'Nørregade 27, 1. th.',
    city: 'Aalborg',
    postalCode: '9000',
    price: 895_000,
    monthlyPayment: 3_200,
    type: 'andelsbolig',
    area: 64,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 1923,
    energyLabel: 'E',
    images: [
      'https://picsum.photos/seed/p004a/800/600',
      'https://picsum.photos/seed/p004b/800/600',
    ],
    description: 'Klassisk andelslejlighed med masser af charme i historisk ejendom. Høje lofter, originale trægulve og tæt på alt hvad Aalborg har at byde på.',
    features: ['Høje lofter', 'Originale trægulve', 'Charme', 'Tæt på centrum', 'Kælder'],
    daysOnMarket: 8,
    agent: { name: 'Poul Nielsen', company: 'Danbolig Aalborg', phone: '98 45 67 89' },
  },
  {
    id: 'p005',
    title: 'Romslig villa med fjordudsigt',
    address: 'Lindholmsvej 23',
    city: 'Nørresundby',
    postalCode: '9400',
    price: 2_495_000,
    monthlyPayment: 8_900,
    type: 'villa',
    area: 140,
    landArea: 650,
    rooms: 5,
    bathrooms: 2,
    yearBuilt: 1978,
    energyLabel: 'D',
    images: [
      'https://picsum.photos/seed/p005a/800/600',
      'https://picsum.photos/seed/p005b/800/600',
    ],
    description: 'Smuk villa med delvis fjordudsigt og stor sydvendt have. Renoveret køkken og badeværelse, dobbelgarage og god plads til hele familien.',
    features: ['Fjordudsigt', 'Dobbelgarage', 'Sydvendt have', 'Renoveret', 'Brændeovn', 'Stor terrasse'],
    daysOnMarket: 35,
    agent: { name: 'Anni Sørensen', company: 'Nybolig Nørresundby', phone: '98 56 78 90' },
  },
  {
    id: 'p006',
    title: 'Moderne lejlighed med udsigt',
    address: 'Karolinelundsvej 5, 2. tv.',
    city: 'Nørresundby',
    postalCode: '9400',
    price: 1_195_000,
    monthlyPayment: 4_300,
    type: 'lejlighed',
    area: 72,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 2015,
    energyLabel: 'A',
    images: [
      'https://picsum.photos/seed/p006a/800/600',
      'https://picsum.photos/seed/p006b/800/600',
    ],
    description: 'Energirigtig lejlighed i nyere byggeri med storslået udsigt over Limfjorden. Åbent køkken-alrum, stor altan og tæt på bus og letbane.',
    features: ['Fjordudsigt', 'Stor altan', 'Elevator', 'Nyt byggeri', 'Varmepumpe', 'Cykelkælder'],
    daysOnMarket: 3,
    agent: { name: 'Knud Larsen', company: 'EDC Nørresundby', phone: '98 67 89 01' },
  },
  {
    id: 'p007',
    title: 'Stor villa i grønne omgivelser',
    address: 'Vandværksvej 14',
    city: 'Hjørring',
    postalCode: '9800',
    price: 1_695_000,
    monthlyPayment: 6_100,
    type: 'villa',
    area: 130,
    landArea: 740,
    rooms: 5,
    bathrooms: 2,
    yearBuilt: 1970,
    energyLabel: 'E',
    images: [
      'https://picsum.photos/seed/p007a/800/600',
      'https://picsum.photos/seed/p007b/800/600',
    ],
    description: 'Solid murstenshus med god plads og stor have. Velholdt ejendom med potentiale for personligt præg. Rolig villavej tæt på skole og indkøb.',
    features: ['Stor have', 'Carport', 'Brændeovn', 'Kælder', 'Anneks', 'Frugtplantage'],
    daysOnMarket: 28,
    agent: { name: 'Birgit Thomsen', company: 'Home Hjørring', phone: '98 78 90 12' },
  },
  {
    id: 'p008',
    title: 'Velfungerende rækkehus',
    address: 'Planteavlsvej 7',
    city: 'Hjørring',
    postalCode: '9800',
    price: 1_095_000,
    monthlyPayment: 3_950,
    type: 'rækkehus',
    area: 98,
    landArea: 180,
    rooms: 4,
    bathrooms: 1,
    yearBuilt: 1985,
    energyLabel: 'C',
    images: [
      'https://picsum.photos/seed/p008a/800/600',
      'https://picsum.photos/seed/p008b/800/600',
    ],
    description: 'Funktionelt rækkehus i god stand med lille privat have. Fornuftigt indrettet med 4 værelser og opdateret badeværelse. Ideel for den lille familie.',
    features: ['Have', 'Parkering', 'Opdateret badeværelse', 'Tæt på skole', 'Redskabsskur'],
    daysOnMarket: 45,
    agent: { name: 'Jens Mortensen', company: 'RealMæglerne Hjørring', phone: '98 89 01 23' },
  },
  {
    id: 'p009',
    title: 'Lys villa nær havnen',
    address: 'Søndergade 45',
    city: 'Frederikshavn',
    postalCode: '9900',
    price: 1_395_000,
    monthlyPayment: 5_000,
    type: 'villa',
    area: 118,
    landArea: 520,
    rooms: 4,
    bathrooms: 1,
    yearBuilt: 1958,
    energyLabel: 'E',
    images: [
      'https://picsum.photos/seed/p009a/800/600',
      'https://picsum.photos/seed/p009b/800/600',
    ],
    description: 'Velholdt villa tæt på havn og centrum. Klassisk dansk arkitektur med masser af charme. Have mod vest og carport. Nyrenoveret køkken.',
    features: ['Nyrenoveret køkken', 'Carport', 'Have mod vest', 'Tæt på havn', 'Brændeovn'],
    daysOnMarket: 18,
    agent: { name: 'Dorte Hansen', company: 'Nybolig Frederikshavn', phone: '98 90 12 34' },
  },
  {
    id: 'p010',
    title: 'Havnefront lejlighed',
    address: 'Havnepladsen 3, 1. tv.',
    city: 'Frederikshavn',
    postalCode: '9900',
    price: 895_000,
    monthlyPayment: 3_200,
    type: 'lejlighed',
    area: 65,
    rooms: 2,
    bathrooms: 1,
    yearBuilt: 1999,
    energyLabel: 'C',
    images: [
      'https://picsum.photos/seed/p010a/800/600',
      'https://picsum.photos/seed/p010b/800/600',
    ],
    description: 'Hyggelig lejlighed med delvis havudsigt og masser af charme. Tæt på alle byens faciliteter og offentlig transport til Aalborg.',
    features: ['Havudsigt', 'Altan', 'Parkering', 'Tæt på centrum', 'Elevator'],
    daysOnMarket: 60,
    agent: { name: 'Torben Jensen', company: 'EDC Frederikshavn', phone: '98 01 23 45' },
  },
  {
    id: 'p011',
    title: 'Idyllisk villa i Thisted',
    address: 'Vildsundvej 8',
    city: 'Thisted',
    postalCode: '7700',
    price: 1_195_000,
    monthlyPayment: 4_300,
    type: 'villa',
    area: 125,
    landArea: 680,
    rooms: 5,
    bathrooms: 1,
    yearBuilt: 1968,
    energyLabel: 'D',
    images: [
      'https://picsum.photos/seed/p011a/800/600',
      'https://picsum.photos/seed/p011b/800/600',
    ],
    description: 'Charmerende villa i rolige omgivelser med dejlig have. God stand med nyt tag og varmepumpe. Perfekt for familien der søger ro og plads.',
    features: ['Nyt tag', 'Varmepumpe', 'Stor have', 'Garage', 'Tæt på fjord', 'Frugttræer'],
    daysOnMarket: 22,
    agent: { name: 'Inge Madsen', company: 'Home Thisted', phone: '97 12 34 56' },
  },
  {
    id: 'p012',
    title: 'Landejendom med mark og skov',
    address: 'Dragsbækvej 42',
    city: 'Thisted',
    postalCode: '7700',
    price: 2_195_000,
    monthlyPayment: 7_900,
    type: 'landejendom',
    area: 210,
    landArea: 52_000,
    rooms: 7,
    bathrooms: 2,
    yearBuilt: 1912,
    energyLabel: 'F',
    images: [
      'https://picsum.photos/seed/p012a/800/600',
      'https://picsum.photos/seed/p012b/800/600',
    ],
    description: 'Historisk gård med 5,2 ha jord, mark og skov. Stuehuset er renoveret med respekt for de originale materialer. Laden og stald i god stand. Unik mulighed.',
    features: ['5,2 ha jord', 'Renoveret stuehus', 'Lade', 'Stald', 'Brønde', 'Skov', 'Mark'],
    daysOnMarket: 90,
    agent: { name: 'Ole Vestergaard', company: 'Danbolig Thisted', phone: '97 23 45 67' },
  },
  {
    id: 'p013',
    title: 'Familievilla i Brønderslev',
    address: 'Algade 78',
    city: 'Brønderslev',
    postalCode: '9700',
    price: 1_495_000,
    monthlyPayment: 5_400,
    type: 'villa',
    area: 135,
    landArea: 600,
    rooms: 5,
    bathrooms: 2,
    yearBuilt: 1982,
    energyLabel: 'C',
    images: [
      'https://picsum.photos/seed/p013a/800/600',
      'https://picsum.photos/seed/p013b/800/600',
    ],
    description: 'Velindrettet familievilla centralt i Brønderslev. To badeværelser, nyrenoveret og i fin stand. Stor have med legehus og terrasse.',
    features: ['2 badeværelser', 'Nyrenoveret', 'Legehus', 'Terrasse', 'Dobbelgarage', 'Varmepumpe'],
    daysOnMarket: 15,
    agent: { name: 'Hanne Christoffersen', company: 'Nybolig Brønderslev', phone: '98 34 56 78' },
  },
  {
    id: 'p014',
    title: 'Eksklusiv villa i Skagen',
    address: 'Fyrrelystvej 12',
    city: 'Skagen',
    postalCode: '9990',
    price: 4_295_000,
    monthlyPayment: 15_500,
    type: 'villa',
    area: 172,
    landArea: 900,
    rooms: 6,
    bathrooms: 3,
    yearBuilt: 2003,
    energyLabel: 'B',
    images: [
      'https://picsum.photos/seed/p014a/800/600',
      'https://picsum.photos/seed/p014b/800/600',
    ],
    description: 'Luksuriøs villa i Skagens populære sommerhuskvarter. Fuld af lys og moderne finish med tre badeværelser og stort udekøkken. Gåafstand til strand og by.',
    features: ['Gåafstand til strand', 'Udekøkken', '3 badeværelser', 'Dobbelt carport', 'Jacuzzi', 'Undervarme'],
    daysOnMarket: 7,
    agent: { name: 'Camilla Lund', company: 'Home Skagen', phone: '98 45 67 89' },
  },
  {
    id: 'p015',
    title: 'Sommerhus med havudsigt',
    address: 'Strandvejen 89',
    city: 'Skagen',
    postalCode: '9990',
    price: 2_895_000,
    monthlyPayment: 10_400,
    type: 'sommerhus',
    area: 95,
    landArea: 1_200,
    rooms: 4,
    bathrooms: 2,
    yearBuilt: 1975,
    energyLabel: 'F',
    images: [
      'https://picsum.photos/seed/p015a/800/600',
      'https://picsum.photos/seed/p015b/800/600',
    ],
    description: 'Autentisk sommerhus med direkte havudsigt og privat adgang til stranden. Hyggelig atmosfære, stor terrasse og brændeovn. Bruges af mange gæster år rundt.',
    features: ['Havudsigt', 'Strandadgang', 'Brændeovn', 'Stor terrasse', 'Sauna', 'Udendørsbruser'],
    daysOnMarket: 14,
    agent: { name: 'Rasmus Holm', company: 'EDC Skagen', phone: '98 56 78 90' },
  },
  {
    id: 'p016',
    title: 'Charmerende hus i Sæby',
    address: 'Bredgade 34',
    city: 'Sæby',
    postalCode: '9300',
    price: 1_295_000,
    monthlyPayment: 4_650,
    type: 'villa',
    area: 120,
    landArea: 450,
    rooms: 4,
    bathrooms: 1,
    yearBuilt: 1955,
    energyLabel: 'E',
    images: [
      'https://picsum.photos/seed/p016a/800/600',
      'https://picsum.photos/seed/p016b/800/600',
    ],
    description: 'Klassisk dansk villa i hyggelige Sæby med gåafstand til strand og historisk bykerne. God stand, renoveret tag og nyt køkken.',
    features: ['Gåafstand til strand', 'Nyt tag', 'Nyt køkken', 'Carport', 'Have', 'Kælder'],
    daysOnMarket: 40,
    agent: { name: 'Marianne Kjær', company: 'LokalBolig Sæby', phone: '98 67 89 01' },
  },
  {
    id: 'p017',
    title: 'Billig villa i Dronninglund',
    address: 'Slotsgade 16',
    city: 'Dronninglund',
    postalCode: '9330',
    price: 895_000,
    monthlyPayment: 3_200,
    type: 'villa',
    area: 110,
    landArea: 500,
    rooms: 4,
    bathrooms: 1,
    yearBuilt: 1960,
    energyLabel: 'E',
    images: [
      'https://picsum.photos/seed/p017a/800/600',
      'https://picsum.photos/seed/p017b/800/600',
    ],
    description: 'God mulighed for fastprisbolig tæt på Dronninglund Slot og skov. Boligen trænger til lidt kærlighed men har gode knogler og potentiale for det rette projekt.',
    features: ['Tæt på skov', 'Garage', 'Have', 'Kælder', 'Potentiale'],
    daysOnMarket: 75,
    agent: { name: 'Preben Storgaard', company: 'Danbolig Dronninglund', phone: '98 78 90 12' },
  },
  {
    id: 'p018',
    title: 'Havnevilla i Hirtshals',
    address: 'Havnevej 21',
    city: 'Hirtshals',
    postalCode: '9850',
    price: 895_000,
    monthlyPayment: 3_200,
    type: 'villa',
    area: 115,
    landArea: 380,
    rooms: 4,
    bathrooms: 1,
    yearBuilt: 1972,
    energyLabel: 'E',
    images: [
      'https://picsum.photos/seed/p018a/800/600',
      'https://picsum.photos/seed/p018b/800/600',
    ],
    description: 'Velholdt villa med havneflair og nem adgang til strand og natur. Hyggelig have og carport. Gode transportforbindelser til Hjørring og Aalborg.',
    features: ['Tæt på havn', 'Carport', 'Have', 'Strandnær', 'Nyrenoveret badeværelse'],
    daysOnMarket: 55,
    agent: { name: 'Else Lindqvist', company: 'Home Hirtshals', phone: '98 89 01 23' },
  },
  {
    id: 'p019',
    title: 'Nyt rækkehus i Aabybro',
    address: 'Mosegårdsvej 3',
    city: 'Aabybro',
    postalCode: '9440',
    price: 1_195_000,
    monthlyPayment: 4_300,
    type: 'rækkehus',
    area: 108,
    landArea: 200,
    rooms: 4,
    bathrooms: 2,
    yearBuilt: 2019,
    energyLabel: 'A',
    images: [
      'https://picsum.photos/seed/p019a/800/600',
      'https://picsum.photos/seed/p019b/800/600',
    ],
    description: 'Nyere rækkehus med energiklasse A og smarte løsninger. Åbent køkken-alrum, 2 badeværelser og sydvendt have. Tæt på skole og motorvej til Aalborg.',
    features: ['Energiklasse A', 'Sydvendt have', '2 badeværelser', 'Varmepumpe', 'Sol', 'Parkering'],
    daysOnMarket: 9,
    agent: { name: 'Kim Vestergaard', company: 'Nybolig Aabybro', phone: '98 90 12 34' },
  },
  {
    id: 'p020',
    title: 'Sommerhus ved Klim Strand',
    address: 'Klim Strandvej 8',
    city: 'Fjerritslev',
    postalCode: '9690',
    price: 1_095_000,
    monthlyPayment: 3_950,
    type: 'sommerhus',
    area: 78,
    landArea: 1_800,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 1988,
    energyLabel: 'G',
    images: [
      'https://picsum.photos/seed/p020a/800/600',
      'https://picsum.photos/seed/p020b/800/600',
    ],
    description: 'Hyggelig sommerhus 200m fra den populære Klim Strand ved Jammerbugtkysten. Stor grund, stor terrasse og brændeovn til de kølige sommeraftener.',
    features: ['200m fra strand', 'Stor terrasse', 'Brændeovn', 'Stor grund', 'Strandnær', 'Udhus'],
    daysOnMarket: 30,
    agent: { name: 'Lise Mortensen', company: 'EDC Fjerritslev', phone: '97 34 56 78' },
  },
  {
    id: 'p021',
    title: 'Familievilla i Nibe',
    address: 'Nibevej 45',
    city: 'Nibe',
    postalCode: '9240',
    price: 1_395_000,
    monthlyPayment: 5_000,
    type: 'villa',
    area: 128,
    landArea: 580,
    rooms: 5,
    bathrooms: 1,
    yearBuilt: 1975,
    energyLabel: 'D',
    images: [
      'https://picsum.photos/seed/p021a/800/600',
      'https://picsum.photos/seed/p021b/800/600',
    ],
    description: 'Hyggelig villa i naturskønne Nibe ved Limfjorden. Velholdt med god have og carport. Tæt på dejlig natur og nem transport til Aalborg.',
    features: ['Tæt på Limfjorden', 'Carport', 'God have', 'Brændeovn', 'Kælder', 'Ny varmepumpe'],
    daysOnMarket: 25,
    agent: { name: 'Nikolaj Skov', company: 'LokalBolig Nibe', phone: '98 01 23 45' },
  },
  {
    id: 'p022',
    title: 'Penthouse lejlighed i Aalborg',
    address: 'Jernbanegade 5, 5. sal',
    city: 'Aalborg',
    postalCode: '9000',
    price: 2_895_000,
    monthlyPayment: 10_400,
    type: 'lejlighed',
    area: 118,
    rooms: 4,
    bathrooms: 2,
    yearBuilt: 2018,
    energyLabel: 'A',
    images: [
      'https://picsum.photos/seed/p022a/800/600',
      'https://picsum.photos/seed/p022b/800/600',
    ],
    description: 'Eksklusivt penthouse med panoramaudsigt over Aalborg. Luksuriøs indretning med køkkenø, undervarme og stor tagterrasse. Elevator direkte til lejlighed.',
    features: ['Tagterrasse', 'Panoramaudsigt', 'Undervarme', 'Elevator', '2 badeværelser', 'Køkkenø', 'Ekslusivt'],
    daysOnMarket: 4,
    agent: { name: 'Helena Brandt', company: 'Home Premium Aalborg', phone: '98 12 34 56' },
  },
  {
    id: 'p023',
    title: 'Budget lejlighed i Aalborg Øst',
    address: 'Hobrovej 123, St. tv.',
    city: 'Aalborg',
    postalCode: '9000',
    price: 695_000,
    monthlyPayment: 2_500,
    type: 'lejlighed',
    area: 58,
    rooms: 2,
    bathrooms: 1,
    yearBuilt: 1967,
    energyLabel: 'D',
    images: [
      'https://picsum.photos/seed/p023a/800/600',
      'https://picsum.photos/seed/p023b/800/600',
    ],
    description: 'Velfungerende lejlighed til fornuftig pris. Praktisk indrettet med altan og kælder. God transportforbindelse til centrum. God start for førstegangskøber.',
    features: ['Altan', 'Kælder', 'Parkering', 'Tæt på bus', 'Lav månedlig ydelse'],
    daysOnMarket: 10,
    agent: { name: 'Søren Dahl', company: 'Danbolig Aalborg', phone: '98 23 45 67' },
  },
  {
    id: 'p024',
    title: 'Historisk stenhus i Løgstør',
    address: 'Havnegade 8',
    city: 'Løgstør',
    postalCode: '9670',
    price: 795_000,
    monthlyPayment: 2_850,
    type: 'villa',
    area: 115,
    landArea: 420,
    rooms: 4,
    bathrooms: 1,
    yearBuilt: 1903,
    energyLabel: 'F',
    images: [
      'https://picsum.photos/seed/p024a/800/600',
      'https://picsum.photos/seed/p024b/800/600',
    ],
    description: 'Charmerende ældre stenhus i historiske Løgstør ved Limfjorden. Autentisk interiør med originale detaljer. Tæt på havn og fjord. Kræver renovering.',
    features: ['Historisk bygning', 'Tæt på havn', 'Originale detaljer', 'Stor have', 'Potentiale'],
    daysOnMarket: 80,
    agent: { name: 'Finn Petersen', company: 'RealMæglerne Løgstør', phone: '98 34 56 78' },
  },
  {
    id: 'p025',
    title: 'Nybygget villa i Vodskov',
    address: 'Ellevej 3',
    city: 'Vodskov',
    postalCode: '9310',
    price: 2_795_000,
    monthlyPayment: 10_100,
    type: 'villa',
    area: 155,
    landArea: 700,
    rooms: 6,
    bathrooms: 2,
    yearBuilt: 2023,
    energyLabel: 'A',
    images: [
      'https://picsum.photos/seed/p025a/800/600',
      'https://picsum.photos/seed/p025b/800/600',
    ],
    description: 'Nybygget og energirigtigt villa med alle moderne faciliteter. Åbent planløsning, køkkenø med Miele hvidevarer og dobbelgarage. 20 minutters kørsel til Aalborg centrum.',
    features: ['Nybygget 2023', 'Miele hvidevarer', 'Dobbelgarage', 'Undervarme', 'Solceller', 'Smart Home'],
    daysOnMarket: 2,
    agent: { name: 'Jesper Aarup', company: 'Nybolig Vodskov', phone: '98 45 67 89' },
  },
  {
    id: 'p026',
    title: 'Strandnær sommerhus i Blokhus',
    address: 'Fyrrevej 17',
    city: 'Blokhus',
    postalCode: '9492',
    price: 1_895_000,
    monthlyPayment: 6_800,
    type: 'sommerhus',
    area: 88,
    landArea: 1_500,
    rooms: 4,
    bathrooms: 1,
    yearBuilt: 1985,
    energyLabel: 'F',
    images: [
      'https://picsum.photos/seed/p026a/800/600',
      'https://picsum.photos/seed/p026b/800/600',
    ],
    description: 'Populært sommerhusområde 300m fra Blokhus Strand. Hyggelig terrasse med solskærm, stor have med legehus og gode naborelationer.',
    features: ['300m fra strand', 'Legehus', 'Stor terrasse', 'Brændeovn', 'Udhus', 'Carport'],
    daysOnMarket: 21,
    agent: { name: 'Vibeke Dalgaard', company: 'EDC Blokhus', phone: '98 56 78 90' },
  },
  {
    id: 'p027',
    title: 'Centralt beliggende lejlighed',
    address: 'Kong Christians Allé 7, 2. mf.',
    city: 'Aalborg',
    postalCode: '9000',
    price: 1_295_000,
    monthlyPayment: 4_650,
    type: 'lejlighed',
    area: 85,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 1935,
    energyLabel: 'D',
    images: [
      'https://picsum.photos/seed/p027a/800/600',
      'https://picsum.photos/seed/p027b/800/600',
    ],
    description: 'Klassisk aalborgiansk lejlighed i ældre ejendom med høje lofter og store vinduer. Lys og rumlig med originale trægulve og franske altaner.',
    features: ['Høje lofter', 'Originale trægulve', 'Franske altaner', 'Centralvarme', 'Kælder'],
    daysOnMarket: 17,
    agent: { name: 'Gitte Holm', company: 'Home Aalborg', phone: '98 67 89 01' },
  },
  {
    id: 'p028',
    title: 'Landlig idyl nær Rebild',
    address: 'Rebildvej 55',
    city: 'Støvring',
    postalCode: '9530',
    price: 1_895_000,
    monthlyPayment: 6_800,
    type: 'villa',
    area: 148,
    landArea: 1_200,
    rooms: 5,
    bathrooms: 2,
    yearBuilt: 1969,
    energyLabel: 'D',
    images: [
      'https://picsum.photos/seed/p028a/800/600',
      'https://picsum.photos/seed/p028b/800/600',
    ],
    description: 'Skøn villa i grønne omgivelser nær Rebild Bakker. Stor grund med æblehave og bæk. Renoveret køkken og bad. Pendlerafstand til Aalborg.',
    features: ['Tæt på Rebild Bakker', 'Æblehave', 'Bæk', 'Renoveret', 'Garage', 'Skovnær'],
    daysOnMarket: 33,
    agent: { name: 'Ulla Krag', company: 'Danbolig Støvring', phone: '98 78 90 12' },
  },
  {
    id: 'p029',
    title: 'Rækkehus i Hobro',
    address: 'Gåsebækvej 12',
    city: 'Hobro',
    postalCode: '9500',
    price: 1_095_000,
    monthlyPayment: 3_950,
    type: 'rækkehus',
    area: 102,
    landArea: 185,
    rooms: 4,
    bathrooms: 1,
    yearBuilt: 1993,
    energyLabel: 'C',
    images: [
      'https://picsum.photos/seed/p029a/800/600',
      'https://picsum.photos/seed/p029b/800/600',
    ],
    description: 'Velholdt rækkehus i roligt område i Hobro. God stand med opdateret køkken og nyrenoveret badeværelse. Lille privat have og carport.',
    features: ['Opdateret køkken', 'Nyrenoveret bad', 'Carport', 'Privat have', 'Tæt på skole'],
    daysOnMarket: 42,
    agent: { name: 'Bent Nørgaard', company: 'LokalBolig Hobro', phone: '98 89 01 23' },
  },
  {
    id: 'p030',
    title: 'Strandvilla i Løkken',
    address: 'Klitbakkevej 4',
    city: 'Løkken',
    postalCode: '9480',
    price: 3_495_000,
    monthlyPayment: 12_600,
    type: 'villa',
    area: 158,
    landArea: 1_100,
    rooms: 6,
    bathrooms: 2,
    yearBuilt: 1995,
    energyLabel: 'C',
    images: [
      'https://picsum.photos/seed/p030a/800/600',
      'https://picsum.photos/seed/p030b/800/600',
    ],
    description: 'Skønne villa 100m fra Løkkens berømte strand. Panoramaudsigt over Vesterhavet fra stuen og terrassen. Indrettet med god smag og masser af lys.',
    features: ['100m fra strand', 'Havudsigt', 'Panorama', 'Stor terrasse', 'Sauna', 'Carport', 'Pool'],
    daysOnMarket: 11,
    agent: { name: 'Carsten Fog', company: 'Nybolig Løkken', phone: '98 90 12 34' },
  },
  {
    id: 'p031',
    title: 'Nyere lejlighed i Aalborg SV',
    address: 'Sofiendalsvej 82, 1. th.',
    city: 'Aalborg',
    postalCode: '9200',
    price: 1_445_000,
    monthlyPayment: 5_200,
    type: 'lejlighed',
    area: 82,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 2012,
    energyLabel: 'B',
    images: [
      'https://picsum.photos/seed/p031a/800/600',
      'https://picsum.photos/seed/p031b/800/600',
    ],
    description: 'Flot og funktionel lejlighed i velkendt boligkvarter tæt på universitetet og letbanen. Åbent køkken-alrum, stor altan og lys til alle tider.',
    features: ['Tæt på AAU', 'Letbane', 'Stor altan', 'Åbent køkken', 'Elevator', 'Cykelkælder'],
    daysOnMarket: 6,
    agent: { name: 'Nadja Kirkeby', company: 'EDC Aalborg SV', phone: '98 01 23 45' },
  },
  {
    id: 'p032',
    title: 'Andelsbolig i Vestbyen',
    address: 'Vesterbro 89, 3. th.',
    city: 'Aalborg',
    postalCode: '9000',
    price: 745_000,
    monthlyPayment: 5_100,
    type: 'andelsbolig',
    area: 70,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 1928,
    energyLabel: 'E',
    images: [
      'https://picsum.photos/seed/p032a/800/600',
      'https://picsum.photos/seed/p032b/800/600',
    ],
    description: 'Fin andelslejlighed i populære Vestbyen. Tæt på caféer, restauranter og Aalborg Stadion. Opdateret bad og køkken, frisk og klar til indflytning.',
    features: ['Vestbyen', 'Tæt på restauranter', 'Opdateret', 'Fællesvaskeri', 'Høje lofter'],
    daysOnMarket: 13,
    agent: { name: 'Trine Bak', company: 'Home Aalborg', phone: '98 12 34 56' },
  },
];
